### ISSUE TITLE
Could not include builder.table inside topology

### ISSUE THREAD

**Issue by slequeux** [jpzk/mockedstreams#13]
Hi,

When using `builder.table` inside the stream topology, an error is raised.

```
"mockedstream" should "mock ktable" in {
    // Given
    val inputA = Seq(("x", int(1)), ("y", int(2)))
    val inputB = Seq(("x", int(4)), ("y", int(3)))
    def topology(builder: KStreamBuilder): Unit = {
      val table = builder.table(strings, ints, "topic-in-a", "store")
      val streamB = builder.stream(strings, ints, "topic-in-b")

      streamB.leftJoin[Integer, Integer](table, new AddJoiner(), strings, ints)
        .to(strings, ints, "topic-out-a")
    }

    // When
    val builder = MockedStreams()
      .topology(topology)
      .input("topic-in-a", strings, ints, inputA)
      .input("topic-in-b", strings, ints, inputB)
      .stores(Seq("store"))

    // Then
    val expectedA = Seq(("x", int(5)), ("y", int(5)))
    builder.output("topic-out-a", strings, ints, expectedA.size)
      .shouldEqual(expectedA)

    builder.stateTable("store") shouldEqual inputA.toMap
  }
```

When executing this test, I got : 
```
task [0_0] Could not find partition info for topic: topic-in-a
org.apache.kafka.streams.errors.StreamsException: task [0_0] Could not find partition info for topic: topic-in-a
	at org.apache.kafka.streams.processor.internals.ProcessorStateManager.register(ProcessorStateManager.java:169)
	at org.apache.kafka.streams.processor.internals.AbstractProcessorContext.register(AbstractProcessorContext.java:99)
	at org.apache.kafka.streams.state.internals.RocksDBStore.init(RocksDBStore.java:152)
	at org.apache.kafka.streams.state.internals.MeteredKeyValueStore$7.run(MeteredKeyValueStore.java:100)
	at org.apache.kafka.streams.processor.internals.StreamsMetricsImpl.measureLatencyNs(StreamsMetricsImpl.java:188)
	at org.apache.kafka.streams.state.internals.MeteredKeyValueStore.init(MeteredKeyValueStore.java:131)
	at org.apache.kafka.streams.state.internals.CachingKeyValueStore.init(CachingKeyValueStore.java:62)
	at org.apache.kafka.streams.processor.internals.AbstractTask.initializeStateStores(AbstractTask.java:86)
	at org.apache.kafka.streams.processor.internals.StreamTask.<init>(StreamTask.java:141)
	at org.apache.kafka.test.ProcessorTopologyTestDriver.<init>(ProcessorTopologyTestDriver.java:212)
	at com.madewithtea.mockedstreams.MockedStreams$Builder.com$madewithtea$mockedstreams$MockedStreams$Builder$$stream(MockedStreams.scala:109)
	at com.madewithtea.mockedstreams.MockedStreams$Builder$$anonfun$output$1.apply(MockedStreams.scala:56)
	at com.madewithtea.mockedstreams.MockedStreams$Builder$$anonfun$output$1.apply(MockedStreams.scala:53)
	at com.madewithtea.mockedstreams.MockedStreams$Builder.withValidInput(MockedStreams.scala:123)
	at com.madewithtea.mockedstreams.MockedStreams$Builder.output(MockedStreams.scala:53)
	at SomeSpec$$anonfun$1.apply$mcV$sp(SomeSpec.scala:64)
	at SomeSpec$$anonfun$1.apply(SomeSpec.scala:34)
	at SomeSpec$$anonfun$1.apply(SomeSpec.scala:34)
	at org.scalatest.Transformer$$anonfun$apply$1.apply$mcV$sp(Transformer.scala:22)
	at org.scalatest.OutcomeOf$class.outcomeOf(OutcomeOf.scala:85)
	at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
	at org.scalatest.Transformer.apply(Transformer.scala:22)
	at org.scalatest.Transformer.apply(Transformer.scala:20)
	at org.scalatest.FlatSpecLike$$anon$1.apply(FlatSpecLike.scala:1647)
	at org.scalatest.Suite$class.withFixture(Suite.scala:1122)
	at org.scalatest.FlatSpec.withFixture(FlatSpec.scala:1683)
	at org.scalatest.FlatSpecLike$class.invokeWithFixture$1(FlatSpecLike.scala:1644)
	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1656)
	at org.scalatest.FlatSpecLike$$anonfun$runTest$1.apply(FlatSpecLike.scala:1656)
	at org.scalatest.SuperEngine.runTestImpl(Engine.scala:306)
	at org.scalatest.FlatSpecLike$class.runTest(FlatSpecLike.scala:1656)
	at org.scalatest.FlatSpec.runTest(FlatSpec.scala:1683)
	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1714)
	at org.scalatest.FlatSpecLike$$anonfun$runTests$1.apply(FlatSpecLike.scala:1714)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:413)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:390)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:427)
	at org.scalatest.SuperEngine$$anonfun$traverseSubNodes$1$1.apply(Engine.scala:401)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.SuperEngine.traverseSubNodes$1(Engine.scala:401)
	at org.scalatest.SuperEngine.org$scalatest$SuperEngine$$runTestsInBranch(Engine.scala:396)
	at org.scalatest.SuperEngine.runTestsImpl(Engine.scala:483)
	at org.scalatest.FlatSpecLike$class.runTests(FlatSpecLike.scala:1714)
	at org.scalatest.FlatSpec.runTests(FlatSpec.scala:1683)
	at org.scalatest.Suite$class.run(Suite.scala:1424)
	at org.scalatest.FlatSpec.org$scalatest$FlatSpecLike$$super$run(FlatSpec.scala:1683)
	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1760)
	at org.scalatest.FlatSpecLike$$anonfun$run$1.apply(FlatSpecLike.scala:1760)
	at org.scalatest.SuperEngine.runImpl(Engine.scala:545)
	at org.scalatest.FlatSpecLike$class.run(FlatSpecLike.scala:1760)
	at org.scalatest.FlatSpec.run(FlatSpec.scala:1683)
	at org.scalatest.tools.SuiteRunner.run(SuiteRunner.scala:55)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2563)
	at org.scalatest.tools.Runner$$anonfun$doRunRunRunDaDoRunRun$3.apply(Runner.scala:2557)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2557)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
	at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
	at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
	at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
	at org.scalatest.tools.Runner$.run(Runner.scala:883)
	at org.scalatest.tools.Runner.run(Runner.scala)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:138)
	at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
```

The only way I managed to make it work is using a `builder.stream` followed by a `groupByKey(...).aggregate(...)` to transform it to a KTable.

Is there a way to make `builder.table(...)` work properly ?

Thank you
Sylvain

**Comment by jpzk** [comment]
It looks like this is an Kafka test driver issue. Maybe it might be better to ask on the mailing list if this is still an issue
